const container = document.getElementById("container");
container.style.backgroundColor = "yellow";
container.style.margin = "20px";
container.style.padding = "10px";
container.style.fontSize = "18px";
container.style.fontWeight = "bold";
container.style.height = "200px";
container.style.width = "300px";
container.style.color = "blue";
